name: book
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - pandas
  - scipy
  - slycot
  - control
  - sympy
  - tornado
  - jupyter-book
  - jupytext
  - libsqlite == 3.37.*
  
  
