name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    
    # Install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        
    # Build the book
    - name: Build the book
      run: |
        $CONDA/bin/jupyter-book build ./book
    
    # Upload the books HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "book/_build/html"

    # Deploy the book
    - name: Deploy the books HTML to github pages
      id: deployment
      uses: actions/deploy-pages@v2
